name: Release

run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Mise
        uses: jdx/mise-action@v4

      - name: Install packages
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Run check
        run: pnpm check

  package:
    needs: check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        plugin:
          - recognize-claude
          - recognize-deepseek
          - recognize-kimi
          - recognize-openai
          - recognize-openrouter
          - recognize-xai
          - recognize-xiaomimimo
          - recognize-zai
          - translate-claude
          - translate-deepseek
          - translate-kimi
          - translate-openai
          - translate-openrouter
          - translate-xai
          - translate-xiaomimimo
          - translate-zai

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set plugin info
        working-directory: ${{ matrix.plugin }}
        run: |
          echo "NAME=$(jq -r '.id' info.json)" >> "$GITHUB_ENV"
          echo "ICON=$(jq -r '.icon' info.json)" >> "$GITHUB_ENV"

      - name: Package plugin
        uses: vimtor/action-zip@v1
        with:
          files: ${{ matrix.plugin }}/info.json ${{ matrix.plugin }}/main.js ${{ matrix.plugin }}/${{ env.ICON }}
          dest: ${{ env.NAME }}.potext

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.NAME }}.potext
          path: '*.potext'
          if-no-files-found: error

  release:
    needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          files: artifacts/*.potext
          generate_release_notes: true
          fail_on_unmatched_files: true
